# Generated by Django 3.0 on 2019-12-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=10)),
                ('sub_title', models.CharField(max_length=10)),
                ('Images', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('summary', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('Images', models.ImageField(upload_to='images/')),
                ('body', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='specialization',
            old_name='Tile',
            new_name='Title',
        ),
    ]
