# Generated by Django 3.0 on 2019-12-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kweb', '0002_auto_20191213_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='sub_title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='Title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='Title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='summary',
            field=models.CharField(max_length=50),
        ),
    ]
