# Generated by Django 3.0 on 2019-12-31 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kweb', '0003_auto_20191214_0805'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Specialization',
        ),
        migrations.DeleteModel(
            name='Specialty',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
